version: "3.8"

services:
  laravel.test:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: dev
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    container_name: app-l11
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:8000'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
      - '${REVERB_PORT-8080}:8080'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-debug}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
      DB_CONNECTION: 'pgsql'
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
    networks:
      - laravel_11_docker_template_network

  vite:
    image: node:20-alpine
    container_name: vite-l11
    command: /bin/sh -c "cd /var/www/html && npm install && npm run dev"
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      NODE_ENV: development
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_11_docker_template_network
    depends_on:
      - laravel.test

  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: mailpit-l11
    ports:
      - '${FORWARD_MAILPIT_PORT:-1025}:1025'
      - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
    networks:
      - laravel_11_docker_template_network
